import { Controller, Get, Param, ParseUUIDPipe, Query } from '@nestjs/common';
import {
  ApiBadRequestResponse,
  ApiBearerAuth,
  ApiNotFoundResponse,
  ApiOkResponse,
  ApiOperation,
  ApiTags,
  ApiUnauthorizedResponse,
} from '@nestjs/swagger';
import { CurrentUser, type CurrentUserType } from '../common/decorators/current-user.decorator.js';
import { ErrorResponse } from '../signal-engine/dto/responses.dto.js';
import { ListReviewsQueryDto } from './dto/list-reviews-query.dto.js';
import { ReviewPageResponse, ReviewResponse } from './dto/responses.dto.js';
import { ReviewsService } from './reviews.service.js';

@ApiTags('reviews')
@ApiBearerAuth()
@ApiUnauthorizedResponse({ type: ErrorResponse, description: 'Missing or invalid session/bearer token.' })
@Controller('reviews')
export class ReviewsController {
  constructor(private readonly reviews: ReviewsService) {}

  @Get()
  @ApiOperation({
    summary: 'List weekly and monthly reviews',
    description:
      'Cursor-paginated, newest period first. Reviews are generated by a scheduled job after each week or month ends; ' +
      'a period in which the user did nothing has no review. Pass `type` to see only weekly or only monthly ones.',
  })
  @ApiOkResponse({ type: ReviewPageResponse })
  @ApiBadRequestResponse({ type: ErrorResponse, description: '`type`, `limit` or the cursor is malformed.' })
  list(@CurrentUser() user: CurrentUserType, @Query() query: ListReviewsQueryDto) {
    return this.reviews.list(user.id, { type: query.type }, { cursor: query.cursor, limit: query.limit });
  }

  @Get(':id')
  @ApiOperation({ summary: 'Get one review' })
  @ApiOkResponse({ type: ReviewResponse })
  @ApiBadRequestResponse({ type: ErrorResponse, description: '`id` is not a UUID.' })
  @ApiNotFoundResponse({ type: ErrorResponse, description: 'No such review for this user.' })
  get(@CurrentUser() user: CurrentUserType, @Param('id', ParseUUIDPipe) id: string) {
    return this.reviews.get(user.id, id);
  }
}
